export const transition = '0.3s ease-in-out'
export const width = '800px'

export const appColor = '#F5F5F5'
export const appColorHover = '#F5F5F5'
export const backgroundColor = '#DCDCDC'
export const backgroundColorHover = '#DCDCDC'
export const color = '#202020'
export const colorHover = '#202020'
export const accentColor = ''
export const accentColorHover = ''


// export const appColor = '#F5F5F5'
// export const appColorHover = '#F5F5F5'
// export const backgroundColor = '#DCDCDC'
// export const backgroundColorHover = '#DCDCDC'
// export const color = '#202020'
// export const colorHover = '#202020'
// export const accentColor = ''
// export const accentColorHover = ''