export const width = '800px'
export const mediaBreak = '650px'
export const borderRad = '5px'
export const transition = '0.3s ease-in-out'

export const whiteOff = '#F5F5F5'
export const whiteDark = '#E0E0E0'
export const greyLight = '#DCDCDC'
export const greyMedium = '#D0D0D0'
export const greyDark = '#808080'
export const blackOff = '#202020'
export const orangeMedium = '#ffd27f'
